sudo: false
language: go

go:
  - 1.5

branches:
  only:
    - master

before_install:
  - go get golang.org/x/tools/cmd/cover
  
install:
  - go get github.com/smartystreets/goconvey/convey

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
